spring:
  application:
    name: sharding-jdbc-example
  profiles:
    active: dev
    include:
  scan:
    basePackages:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    sharding:
      tables:
        t_log:
          actual-data-nodes: ds0.t_log_$->{2016..2020}
          table-strategy:
            standard:
              sharding-column: create_time
              precise-algorithm-class-name: com.engrz.demo.sharding.jdbc.example.config.DatePreciseModuloShardingTableAlgorithm
              range-algorithm-class-name: com.engrz.demo.sharding.jdbc.example.config.DateRangeModuloShardingTableAlgorithm
logging:
  level:
    root: INFO
    com.engrz.demo.spring.boot: DEBUG
server:
  port: 8080
  http:
    encoding:
      charset: UTF-8
      enabled: true
  tomcat:
    max-threads: 200
    accept-count: 100
    max-connections: 10000
    port-header: X-Forwarded-Port
    uri-encoding: UTF-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl